---
title: "Problem_5"
output: pdf_document

---

You are given that:

* $\varepsilon_t = exp[\int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du ]$
* $\gamma_u$ is assumed to be deterministic and continuous in t and the integral $\int_{0}^{t} \gamma_u \; dW_u$ is well defined
* For all $t \ge 0$, the following non-explosiveness condition holds:
$$ exp(\int_{0}^{t} \gamma_u^2 \; du) < \infty$$
* Under $\mathbb{P}$, $W_t$ is a standard Wiener process  

(a) Determine the distribution of $\int_{0}^{t} \gamma_u \; dW_u$ under $\mathbb{P}$ 
$\int_{0}^{t} \gamma_u \; dW_u$ is an Ito integral. So:
$$\int_{0}^{t} \gamma_u \; dW_u \sim {\sf \mathcal{N}}(0, \int_{0}^{t} \gamma_u^2 \; du)$$
(b) Calculate $E^\mathbb{P}(\varepsilon_t)$
$$E^\mathbb{P}(\varepsilon_t) = E^\mathbb{P}(exp[\int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du ])$$
From part (a), we know this is a log-normal random variable with parameters $\mu = -\frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du$ and $\sigma^2 = \int_{0}^{t} \gamma_u^2 \; du$. So, the expected value of $\varepsilon_t$ is:
$$E^\mathbb{P}(\varepsilon_t) = e^{\mu+\frac{1}{2}\sigma^2}$$
$$E^\mathbb{P}(\varepsilon_t) = e^{-\frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du+\frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du}$$
$$E^\mathbb{P}(\varepsilon_t) = 1$$
(c) Determine the stochastic differential equation for $d\varepsilon_t$ under $\mathbb{P}$

$$ d\varepsilon_t = d[e^{\int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2}\int_{0}^{t} \gamma_u^2 \; du}]$$
Let $Y_t = \int_{0}^{t} \gamma_u \; dW_u$. Then 

$$ \varepsilon_t = f(Y_t, t) = e^{Y_t - \frac{1}{2}\int_{0}^{t} \gamma_u^2 \; du} $$
First, note that:

$$ f_t = -\frac{1}{2} \gamma_t^2 \varepsilon_t $$
$$ f_{Y_t} = f_{Y_tY_t} = \varepsilon_t $$
$$d_{Y_t} = \gamma_t dW_t$$
$$(d_{Y_t})^2 = \gamma_t^2 dt$$
Then using Ito's lemma:
$$ d\varepsilon_t = f_t dt + f_{Y_t} dY_t + \frac{1}{2} f_{Y_tY_t}(dY_t)^2 $$
$$ = -\frac{1}{2} \gamma_t^2 \varepsilon_t dt + \varepsilon_t dY_t + \frac{1}{2} \varepsilon_t (dY_t)^2 $$

$$ = -\frac{1}{2} \gamma_t^2 \varepsilon_t dt + \varepsilon_t \gamma_t dW_t + \frac{1}{2} \varepsilon_t \gamma_t^2 dt $$

$$ = \varepsilon_t \gamma_t dW_t  $$

Therefore, 
$$d\varepsilon_t = \varepsilon_t \gamma_t dW_t $$
(d) Simplify the following quantity: $E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u - \frac{1}{2} \int_{0}^{t}(\alpha + \gamma_u)^2du)]$

The quantity is log-normally distributed since $\int_{0}^{t} (\alpha + \gamma_u) dW_u$ is an Ito integral. 
The mean of a log-normal distribution is $e^{\mu + \frac{1}{2} \sigma^2}$

$$ \mu = - \frac{1}{2} \int_{0}^{t}(\alpha + \gamma_u)^2du  $$
$$ \sigma^2 = \int_{0}^{t} (\alpha + \gamma_u)^2 du$$
$$E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u - \frac{1}{2} \int_{0}^{t}(\alpha + \gamma_u)^2du)] = exp(- \frac{1}{2} \int_{0}^{t}(\alpha + \gamma_u)^2du + \frac{1}{2} \int_{0}^{t} (\alpha + \gamma_u)^2 du) $$
$$  = e^0 = 1 $$


Additionally you are given that: $\overline{W_t} = W_t - \int_{0}^{t} \gamma_u du$    

(e) Prove that:
$$ E^\mathbb{Q}[exp(\alpha \overline{W_t})] = E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u - \frac{1}{2} \int_{0}^{t}(2\alpha\gamma_u + \gamma_u^2)du)] = e^{\frac{\alpha^2t}{2}}$$
$$ E^\mathbb{Q}[exp(\alpha \overline{W_t})] = E^\mathbb{Q}[exp(\alpha(W_t - \int_{0}^{t} \gamma_u du))]$$
To convert between $\mathbb{Q}$ and $\mathbb{P}$ one must multiply by the Radon-Nikodym derivative,
$$E^\mathbb{Q}[exp(\alpha \overline{W_t})] = E^\mathbb{P}[exp(\alpha(W_t - \int_{0}^{t} \gamma_u du) + \int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du )]$$
$$ = E^\mathbb{P}[exp(\alpha W_t - \int_{0}^{t} \alpha \gamma_u du + \int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du )] $$
$$ = E^\mathbb{P}[exp(\int_{0}^{t} \alpha dW_u - \int_{0}^{t} \alpha \gamma_u du + \int_{0}^{t} \gamma_u \; dW_u - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du )] $$
$$ = E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u - \int_{0}^{t} \alpha \gamma_u du - \frac{1}{2} \int_{0}^{t} \gamma_u^2 \; du )] $$
$$ = E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u    - \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du )] $$
So, 

$$ E^\mathbb{Q}[exp(\alpha \overline{W_t})] = E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u    - \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du )]$$
Note, $exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u    - \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2) \; du )$ is log-normally distributed. So,

$$ \mu = - \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du $$
$$ \sigma^2 = \int_{0}^{t} (\alpha + \gamma_u)^2 du$$
$$E^\mathbb{P}[exp(\int_{0}^{t} (\alpha + \gamma_u) dW_u    - \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du )] = e^{\mu + \frac{1}{2} \sigma^2} $$
$$= exp(- \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du + \frac{1}{2} \int_{0}^{t} (\alpha + \gamma_u)^2 du)$$
$$ = exp(- \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du + \frac{1}{2} \int_{0}^{t} (\alpha^2 + 2\alpha\gamma_u+\gamma_u^2) du)$$
$$ = exp(- \frac{1}{2} \int_{0}^{t} (2\alpha \gamma_u + \gamma_u^2 )\; du + \frac{1}{2} \int_{0}^{t} (2\alpha\gamma_u+\gamma_u^2) du + \frac{1}{2}\int_{0}^{t}\alpha^2 du)$$
$$ = exp(\frac{1}{2}\int_{0}^{t}\alpha^2 du)$$
$$ = e^{\frac{\alpha^2t}{2}}$$
(f) Identify the distribution of $\over{W_t}$ under the probability measure $\mathbb{Q}$.  
$\over{W_t}$ is normally distributed with mean $\mu= 0$ and variance $\sigma^2 = t$.  

(g) Is the Radon-Nikodym derivative a martingale under $\mathbb{P}$?  
Yes, the Radob-Nikodym derivative is a martingale under $\mathbb{P}$. We can see this from part (c). The stochastic differential equation $d\epsilon_t$ has no drift term. 

(h) Suppose that $\gamma_t=0$ for all t. In this case, what is the value of the Radon-Nikodym derivative?  
The value of the Radon-Nikodym derivative is
$$\varepsilon_t = e^{\int_{0}^{t}\gamma_u \;dW_u - \frac{1}{2}\int_{0}^{t} \gamma_u^2 \;du}$$
$$ = e^{0} = 1$$