---
title: "Problem_8"
output: pdf_document
date: "2025-04-08"
---

Insurance company XYZ has hired you to help manage the financial risks of its newly created variable annuity blcok. The company recently introduced a variable annuity contract with a Guaranteed Minimum Accumulation Benefity (GMAB).  
* Under GMAB, if the policyholder's account value in three years is less than 95% of the initial premium amount, then the account value will be reset to 95% of the initial premium.  

(a) Your manager is interested in learning about how the volatility term structure changes when markets crash. Compare the implied volatilities of short and long-term options under "normal" market conditions with their levels under "extreme" conditions. 

* Under normal market conditions, the volatility term structure is upward sloping. That is the implied volatilities of long-term options exceed those of short-term options.  
* During extreme market conditions, the volatility term structure may become more flat or even inverted. Investors may expect a return to normalcy so they may expect volatility to decline over the long-term during extreme market events.  

The Company currently models the implied volatility at time t for an option on the S&P 500 Index expiring at time T with the following formula: 
$$\sigma_{t,T} = 0.2 + (0.01 + 0.1T) |\frac{K}{S_t} - 1|$$
$$T = \mbox{ remaining time to maturity of the option }$$
$$K = \mbox{ strike price}$$
$$S_t = \mbox{ index valute at time t }$$

(b) Describe two differences between this specification of implied volatility and the empirically observed shape of volatility smiles. 
1. The curvature of the volatility smile is the same for out of the money calls and out of the money puts. Empirically, the curvature for out of the money puts exceeds that of out of the money calls. 
2. The curvature of the volatility smile is more pronounced for longer maturities. Empirically, the skew starts to taper off and become less curved for longer maturities.  

You are also given the following market assumptions:   
* The current index level at issue is $S_0 = 100$   
* The dividend rate $\delta = 0%$  
* The risk-free rate $r= 3 \%$  
* $\mbox{ Mortality Rate} = 3 \%$  
* $ \mbox{ Lapse Rate} = 4 \%$ in year 1, and 8% in years 2 and 3  

(c) Calculate the delta of the GMAB of a variable annuity contract written on the S&P 500 immediately after the contract is issued. 

$$\Delta_{decremented} = \Delta_{undecremented} * x$$
$$ x = \mbox{ precentage of policyholders still expected to be active after 3 years}$$
$\Delta_{undecremented}$ for a put when volatility is not constant is:
$$\Delta_{undecremented} = (N(d_1)-1) + \displaystyle \frac{\partial Black(S,T,K;\sigma_{impl}(S,K))}{\partial \sigma_{impl}(S,K)} \displaystyle \frac{\partial \sigma_{impl}(S,K)}{\partial S}$$

$$\sigma_{0,3} = 0.2 + (0.01 + .1(3)) |\frac{95}{100} - 1| $$
$$ = 0.2155$$
Since $\frac{K}{S_0} - 1 < 0$, $|\frac{K}{S_0}-1| = -(\frac{K}{S_0}-1)$.
$$\displaystyle \frac{\partial \sigma_{impl}(S,K)}{\partial S} = \frac{(.01+.1T)K}{S_0^2} $$
$$ = \frac{(.01+.1(3))95}{100^2} = 0.002945$$
$$d_1 = \frac{ln(\frac{S}{K})+(r+0.5\sigma_{0,T}^2)T}{\sigma_{0,T} \sqrt{T}}$$
$$= \frac{ln(\frac{100}{95})+(.03+0.5(.2155)^2)(3)}{.2155 \sqrt{3}} = .5652$$

$$N(d_1) = N(.5652) = .7140$$
$$\displaystyle \frac{\partial Black(S,T,K,r;\sigma_{impl}(S,K))}{\partial \sigma_{impl}(S,K)} = S_0 \sqrt{T} N'(d_1)$$
$$ = S_0 \sqrt{T} \frac{e^{\frac{d_1^2}{2}}}{\sqrt{2\pi}}=100\sqrt{3}\frac{e^{-\frac{.5652^2}{2}}}{\sqrt{2\pi}} = 58.8993 $$
$$\Delta_{undecremented} = (N(d_1)-1) + \displaystyle \frac{\partial Black(S,T,K;\sigma_{impl}(S,K))}{\partial \sigma_{impl}(S,K)} \displaystyle \frac{\partial \sigma_{impl}(S,K)}{\partial S}$$
$$ = (.7140 - 1) + 58.8993(.002945) = -0.11252$$

$$\Delta_{decremented} = -.11252(.98)^3(.96)(.92)^2 =-0.08605$$
