---
title: "Problem_7"
output: pdf_document
date: "2025-04-02"
---

The market risk actuary for an insurance company is looking at different short rate models to use to model interest rates for pricing variable annuity guarantees. The model that has traditionally been used is the Vasicek model with dynamics given by:  
$$dr_t = \gamma(\overline{r} - r_t)dt + \sigma dX_t$$
The market risk actuary calibrates the model to zero-coupon bond prices observed in the market to determine that $\gamma=0.2$, $\overline{r}=0.04$, and $\sigma=0.05$. Assume the current value of the instantaneous short-rate is $r_0=0.03$.  

(a) Determine the risk-neutral probability that the instantaneous short rate will be negative in 4 years. 

$$E[r_t]=r_0e^{-\gamma t} + \overline{r}(1-e^{- \gamma t})$$
$$= .03 e^{-.2(4)} + .04 (1 - e^{-.2(4)})$$
$$=.035507$$

$$Var[r_t] = \frac{\sigma ^ 2}{2 \gamma}(1 - e^{-2 \gamma t})$$
$$= \frac{.05^2}{2(.2)}(1-e^{-2(.2)(4)})$$
$$= .004988$$

$$P[r_4 < 0] = P[\frac{r_4 - \mu}{\sigma} < \frac{0 - \mu}{\sigma}]$$
$$= P[Z < \frac{0 - .035507}{\sqrt{.004988}}]$$
$$= \Phi(-0.50274)$$
$$= .30757$$

(b) Describe the strengths and weaknesses of using the Vasicek model for modeling interest rates.  
* Strengths:
    + **Mean Reverting**- the model is mean reverting which matches the empirical behavior for interest rates. 
    + **Simple** - the model is simple and easy to understand. 
    + **Analytically Tractable** - the model is analytically tractable and has closed form formulas for zero-coupon bond prices and certain interest rate derivatives. 
* Weaknesses:
    + **Single Factor Model** - the Vasicek model is a single factor model. So it is only able to model parallel movements in the yield curve and is unable to match more complex dynamics of the yield curve. 
    + **Unable to reproduce market term structure** - The standard Vasicek model is unable to reproduce the market term structure of zero-coupon bonds. 
    + **Negative Interest Rates** - the Vasicek model allows for negative interest rates. Which is incompatible with the empirical evidence. 
  
(c) The market risk actuary would like a one factor interest rate model that does not allow for negative interest rates.  Describe two alternative models the market risk actuary could use. 
  Two alternative one factor interest rate models that do not allow for negative interest rates are:
* **Cox-Ingersoll-Ross** - An extension of the Vasicek model that eliminates the possibility of negative interest rates.
    + $dr_t=\gamma(\overline{r} - r_t)dt + \sigma \sqrt{r_t}dX_t$
* **Black-Karasinski** - A log-normal interest rate model. 
    + $y_t = ln(r_t)$
    + $dy_t = (\theta_t - \gamma_t y_t)dt + \sigma_tdX_t$

(d) How can the market risk actuary modify the Vasicek model so that it can reproduce zero-coupon bond prices observed in the market. 

  The actuary could make the parameters of the Vasicek model time dependent. Then he could select the parameters such that the zero-coupon bond prices produced by the model match the observed market zer0-coupon bond prices. 
  
(e) Describe the advantages of using a two factor model over using a one factor model for interest rates. 
1. A two factor model allows you to model changes in the term structure of interest rates in addition to parallel shifts in the yield curve. 
2. Two factor models can reproduce zero-coupon bond prices and the initial term structure observed in the market. 

(f) From all the models suggested so far, make a recommendation for which interest rate model the company should use going forward. Justify your answer.  
* I would recommend the company use a two factor Hull-White model
* Since it is a two factor model it is able to model both parallel changes in the yield curve and changes in the term structure of interest rates
* The model is analytically tractable with formulas for zero-coupon bond prices and certain interest rate derivatives. 
* The model is able to match the market observed zero-coupon bond prices and term structure.
* The model can also be calibrated to the volatility term structure. 
  
    
